### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by Username77177** [he-mat/better_tutorial#1]
Hey! Can I fork your repository for translation? What *license* does your repository has? Can I copy it and modify?

**Comment by he-mat** [comment]
I haven't touched this repo in a couple of years. Go ahead and translate the repo, use the code, do whatever. I don't care if you claim that you wrote it. You don't have to link the repo. Have a nice time!

**Comment by Username77177** [comment]
Oh, thanks, bro
